exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("players")
    .then(function () {
      // Inserts seed entries
      return knex("players").insert([
        {
          playerID: "DT-1231",
          playerFirst: "Darwin",
          playerLast: "Thompson",
          playerFull: "Darwin Thompson",
          position: "RB",
          startYear: 2019,
          currentTeam: "KC",
          height: 69,
          weight: 195,
          dob: "2/12/97",
          forty: 4.55,
          bench: 23,
          vertical: 39.0,
          broad: 126,
          shuttle: 4.3,
          cone: 6.93,
          arm: 29.75,
          hand: 8.38,
          dpos: 214.0,
          col: "Utah State",
          dv: "Mountain West (MWC)",
          jnum: 34,
          dcp: 3,
        },
        {
          playerID: "DT-1992",
          playerFirst: "De'Lance",
          playerLast: "Turner",
          playerFull: "De'Lance Turner",
          position: "RB",
          startYear: 2018,
          currentTeam: "MIA",
          height: 73,
          weight: 214,
          dob: "8/23/95",
          forty: 4.55,
          bench: 24,
          vertical: 37.0,
          broad: 120,
          shuttle: 4.45,
          cone: 7.48,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Alcorn State",
          dv: "Southwestern Athletic (SWAC)",
          jnum: 34,
          dcp: 2,
        },
        {
          playerID: "DV-0550",
          playerFirst: "Dan",
          playerLast: "Vitale",
          playerFull: "Dan Vitale",
          position: "RB",
          startYear: 2016,
          currentTeam: "GB",
          height: 73,
          weight: 239,
          dob: "10/26/93",
          forty: 4.52,
          bench: 30,
          vertical: 38.5,
          broad: 123,
          shuttle: 4.12,
          cone: 7.12,
          arm: 31.75,
          hand: 9.75,
          dpos: 197.0,
          col: "Northwestern",
          dv: "Big Ten",
          jnum: 45,
          dcp: 1,
        },
        {
          playerID: "DW-1350",
          playerFirst: "DeAndre",
          playerLast: "Washington",
          playerFull: "DeAndre Washington",
          position: "RB",
          startYear: 2016,
          currentTeam: "OAK",
          height: 68,
          weight: 204,
          dob: "2/22/93",
          forty: 4.46,
          bench: 24,
          vertical: 34.5,
          broad: 118,
          shuttle: 4.2,
          cone: 7.03,
          arm: 30.0,
          hand: 9.0,
          dpos: 143.0,
          col: "Texas Tech",
          dv: "Big 12",
          jnum: 33,
          dcp: 3,
        },
        {
          playerID: "DW-1550",
          playerFirst: "Dwayne",
          playerLast: "Washington",
          playerFull: "Dwayne Washington",
          position: "RB",
          startYear: 2016,
          currentTeam: "NO",
          height: 73,
          weight: 223,
          dob: "4/24/94",
          forty: 4.42,
          bench: 21,
          vertical: 37.5,
          broad: 127,
          shuttle: 4.22,
          cone: 6.85,
          arm: 0.0,
          hand: 0.0,
          dpos: 236.0,
          col: "Washington",
          dv: "Pacific 12",
          jnum: 27,
          dcp: 3,
        },
        {
          playerID: "DW-1750",
          playerFirst: "Derek",
          playerLast: "Watt",
          playerFull: "Derek Watt",
          position: "RB",
          startYear: 2016,
          currentTeam: "LAC",
          height: 74,
          weight: 235,
          dob: "11/7/92",
          forty: 4.75,
          bench: 19,
          vertical: 33.5,
          broad: 116,
          shuttle: 4.29,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 198.0,
          col: "Wisconsin",
          dv: "Big Ten",
          jnum: 34,
          dcp: 1,
        },
        {
          playerID: "DW-3125",
          playerFirst: "Damien",
          playerLast: "Williams",
          playerFull: "Damien Williams",
          position: "RB",
          startYear: 2014,
          currentTeam: "KC",
          height: 71,
          weight: 222,
          dob: "4/3/92",
          forty: 4.45,
          bench: 16,
          vertical: 35.5,
          broad: 121,
          shuttle: 4.25,
          cone: 7.37,
          arm: 30.63,
          hand: 9.13,
          dpos: 0.0,
          col: "Oklahoma",
          dv: "Big 12",
          jnum: 26,
          dcp: 3,
        },
        {
          playerID: "DW-3243",
          playerFirst: "Darrel",
          playerLast: "Williams",
          playerFull: "Darrel Williams",
          position: "RB",
          startYear: 2018,
          currentTeam: "KC",
          height: 72,
          weight: 225,
          dob: "4/15/95",
          forty: 4.72,
          bench: 22,
          vertical: 32.0,
          broad: 109,
          shuttle: 4.21,
          cone: 7.2,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "LSU",
          dv: "Southeastern (SEC)",
          jnum: 31,
          dcp: 3,
        },
        {
          playerID: "DW-3906",
          playerFirst: "Dexter",
          playerLast: "Williams",
          playerFull: "Dexter Williams",
          position: "RB",
          startYear: 2019,
          currentTeam: "GB",
          height: 71,
          weight: 212,
          dob: "1/6/97",
          forty: 4.57,
          bench: 17,
          vertical: 36.0,
          broad: 130,
          shuttle: 4.16,
          cone: 7.0,
          arm: 32.25,
          hand: 9.63,
          dpos: 194.0,
          col: "Notre Dame",
          dv: "FBS Independents",
          jnum: 22,
          dcp: 3,
        },
        {
          playerID: "EE-0250",
          playerFirst: "Ezekiel",
          playerLast: "Elliott",
          playerFull: "Ezekiel Elliott",
          position: "RB",
          startYear: 2016,
          currentTeam: "DAL",
          height: 72,
          weight: 225,
          dob: "7/22/95",
          forty: 4.45,
          bench: 0,
          vertical: 32.5,
          broad: 118,
          shuttle: 0.0,
          cone: 0.0,
          arm: 31.25,
          hand: 9.25,
          dpos: 4.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 21,
          dcp: 1,
        },
        {
          playerID: "EP-0350",
          playerFirst: "Elijhaa",
          playerLast: "Penny",
          playerFull: "Elijhaa Penny",
          position: "RB",
          startYear: 2016,
          currentTeam: "NYG",
          height: 73,
          weight: 233,
          dob: "8/17/93",
          forty: 4.81,
          bench: 21,
          vertical: 28.5,
          broad: 108,
          shuttle: 4.55,
          cone: 7.2,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Idaho",
          dv: "Sun Belt",
          jnum: 39,
          dcp: 2,
        },
        {
          playerID: "FG-0200",
          playerFirst: "Frank",
          playerLast: "Gore",
          playerFull: "Frank Gore",
          position: "RB",
          startYear: 2005,
          currentTeam: "BUF",
          height: 69,
          weight: 217,
          dob: "5/14/83",
          forty: 4.55,
          bench: 0,
          vertical: 34.0,
          broad: 109,
          shuttle: 4.11,
          cone: 6.91,
          arm: 0.0,
          hand: 0.0,
          dpos: 65.0,
          col: "Miami (FL)",
          dv: "Atlantic Coast (ACC)",
          jnum: 20,
          dcp: 1,
        },
        {
          playerID: "GB-0350",
          playerFirst: "Giovani",
          playerLast: "Bernard",
          playerFull: "Giovani Bernard",
          position: "RB",
          startYear: 2013,
          currentTeam: "CIN",
          height: 68,
          weight: 202,
          dob: "11/22/91",
          forty: 4.5,
          bench: 19,
          vertical: 33.5,
          broad: 122,
          shuttle: 4.12,
          cone: 6.91,
          arm: 28.0,
          hand: 9.38,
          dpos: 37.0,
          col: "North Carolina",
          dv: "Atlantic Coast (ACC)",
          jnum: 25,
          dcp: 2,
        },
        {
          playerID: "GE-0150",
          playerFirst: "Gus",
          playerLast: "Edwards",
          playerFull: "Gus Edwards",
          position: "RB",
          startYear: 2018,
          currentTeam: "BAL",
          height: 73,
          weight: 235,
          dob: "4/13/95",
          forty: 4.53,
          bench: 17,
          vertical: 34.5,
          broad: 123,
          shuttle: 4.24,
          cone: 7.22,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Rutgers",
          dv: "Big Ten",
          jnum: 35,
          dcp: 2,
        },
        {
          playerID: "GH-1162",
          playerFirst: "Gregory",
          playerLast: "Howell",
          playerFull: "Gregory Howell",
          position: "RB",
          startYear: 2018,
          currentTeam: "HOU",
          height: 73,
          weight: 215,
          dob: "3/27/96",
          forty: 4.58,
          bench: 19,
          vertical: 27.5,
          broad: 116,
          shuttle: 4.51,
          cone: 7.55,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Florida Atlantic",
          dv: "Conference USA (C-USA)",
          jnum: 38,
          dcp: 3,
        },
        {
          playerID: "IS-0250",
          playerFirst: "Ito",
          playerLast: "Smith",
          playerFull: "Ito Smith",
          position: "RB",
          startYear: 2018,
          currentTeam: "ATL",
          height: 69,
          weight: 198,
          dob: "9/11/95",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 126.0,
          col: "Southern Mississippi",
          dv: "Conference USA (C-USA)",
          jnum: 25,
          dcp: 2,
        },
        {
          playerID: "JA-0275",
          playerFirst: "Josh",
          playerLast: "Adams",
          playerFull: "Josh Adams",
          position: "RB",
          startYear: 2018,
          currentTeam: "NYJ",
          height: 74,
          weight: 213,
          dob: "10/29/96",
          forty: 4.52,
          bench: 18,
          vertical: 34.0,
          broad: 122,
          shuttle: 0.0,
          cone: 6.78,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Notre Dame",
          dv: "FBS Independents",
          jnum: 36,
          dcp: 4,
        },
        {
          playerID: "JA-0450",
          playerFirst: "Jay",
          playerLast: "Ajayi",
          playerFull: "Jay Ajayi",
          position: "RB",
          startYear: 2015,
          currentTeam: "INA",
          height: 72,
          weight: 221,
          dob: "6/15/93",
          forty: 4.52,
          bench: 19,
          vertical: 39.0,
          broad: 121,
          shuttle: 4.1,
          cone: 7.1,
          arm: 32.0,
          hand: 10.0,
          dpos: 149.0,
          col: "Boise State",
          dv: "Mountain West (MWC)",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "JA-1025",
          playerFirst: "Javorius",
          playerLast: "Allen",
          playerFull: "Javorius Allen",
          position: "RB",
          startYear: 2015,
          currentTeam: "NYG",
          height: 72,
          weight: 221,
          dob: "8/27/91",
          forty: 4.5,
          bench: 11,
          vertical: 35.5,
          broad: 121,
          shuttle: 4.28,
          cone: 6.96,
          arm: 31.75,
          hand: 9.38,
          dpos: 125.0,
          col: "USC",
          dv: "Pacific 12",
          jnum: 37,
          dcp: 4,
        },
        {
          playerID: "JC-4075",
          playerFirst: "James",
          playerLast: "Conner",
          playerFull: "James Conner",
          position: "RB",
          startYear: 2017,
          currentTeam: "PIT",
          height: 73,
          weight: 233,
          dob: "5/5/95",
          forty: 4.65,
          bench: 20,
          vertical: 29.0,
          broad: 113,
          shuttle: 4.4,
          cone: 7.14,
          arm: 31.25,
          hand: 9.88,
          dpos: 105.0,
          col: "Pittsburgh",
          dv: "Atlantic Coast (ACC)",
          jnum: 30,
          dcp: 1,
        },
        {
          playerID: "JD-1650",
          playerFirst: "James",
          playerLast: "Develin",
          playerFull: "James Develin",
          position: "RB",
          startYear: 2010,
          currentTeam: "NE",
          height: 75,
          weight: 260,
          dob: "7/23/88",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Brown",
          dv: "Ivy League",
          jnum: 46,
          dcp: 3,
        },
        {
          playerID: "JF-1250",
          playerFirst: "Josh",
          playerLast: "Ferguson",
          playerFull: "Josh Ferguson",
          position: "RB",
          startYear: 2016,
          currentTeam: "WAS",
          height: 70,
          weight: 198,
          dob: "5/23/93",
          forty: 4.43,
          bench: 21,
          vertical: 34.5,
          broad: 120,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Illinois",
          dv: "Big Ten",
          jnum: 40,
          dcp: 3,
        },
        {
          playerID: "JH-4085",
          playerFirst: "Justice",
          playerLast: "Hill",
          playerFull: "Justice Hill",
          position: "RB",
          startYear: 2019,
          currentTeam: "BAL",
          height: 70,
          weight: 198,
          dob: "11/14/97",
          forty: 4.4,
          bench: 21,
          vertical: 40.0,
          broad: 130,
          shuttle: 0.0,
          cone: 0.0,
          arm: 31.63,
          hand: 9.5,
          dpos: 113.0,
          col: "Oklahoma State",
          dv: "Big 12",
          jnum: 43,
          dcp: 3,
        },
        {
          playerID: "JH-4250",
          playerFirst: "Jonathan",
          playerLast: "Hilliman",
          playerFull: "Jonathan Hilliman",
          position: "RB",
          startYear: 2019,
          currentTeam: "NYG",
          height: 72,
          weight: 220,
          dob: "11/14/95",
          forty: 4.49,
          bench: 20,
          vertical: 34.5,
          broad: 120,
          shuttle: 4.26,
          cone: 7.12,
          arm: 33.0,
          hand: 8.75,
          dpos: 0.0,
          col: "Rutgers",
          dv: "Big Ten",
          jnum: 28,
          dcp: 4,
        },
        {
          playerID: "JH-5575",
          playerFirst: "Jordan",
          playerLast: "Howard",
          playerFull: "Jordan Howard",
          position: "RB",
          startYear: 2016,
          currentTeam: "PHI",
          height: 72,
          weight: 230,
          dob: "11/2/94",
          forty: 4.59,
          bench: 16,
          vertical: 34.0,
          broad: 122,
          shuttle: 4.34,
          cone: 7.14,
          arm: 32.25,
          hand: 9.0,
          dpos: 150.0,
          col: "Indiana",
          dv: "Big Ten",
          jnum: 24,
          dcp: 1,
        },
        {
          playerID: "JJ-0575",
          playerFirst: "Justin",
          playerLast: "Jackson",
          playerFull: "Justin Jackson",
          position: "RB",
          startYear: 2018,
          currentTeam: "LAC",
          height: 72,
          weight: 199,
          dob: "4/22/96",
          forty: 4.52,
          bench: 13,
          vertical: 38.5,
          broad: 122,
          shuttle: 4.07,
          cone: 6.81,
          arm: 30.63,
          hand: 9.25,
          dpos: 251.0,
          col: "Northwestern",
          dv: "Big Ten",
          jnum: 22,
          dcp: 3,
        },
        {
          playerID: "JJ-0587",
          playerFirst: "Josh",
          playerLast: "Jacobs",
          playerFull: "Josh Jacobs",
          position: "RB",
          startYear: 2019,
          currentTeam: "OAK",
          height: 70,
          weight: 220,
          dob: "2/11/98",
          forty: 4.64,
          bench: 18,
          vertical: 35.0,
          broad: 112,
          shuttle: 0.0,
          cone: 0.0,
          arm: 31.63,
          hand: 10.13,
          dpos: 24.0,
          col: "Alabama",
          dv: "Southeastern (SEC)",
          jnum: 28,
          dcp: 1,
        },
        {
          playerID: "JJ-2518",
          playerFirst: "Jakob",
          playerLast: "Johnson",
          playerFull: "Jakob Johnson",
          position: "RB",
          startYear: 2019,
          currentTeam: "NE",
          height: 75,
          weight: 253,
          dob: "12/15/94",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Tennessee",
          dv: "Southeastern (SEC)",
          jnum: 47,
          dcp: 5,
        },
        {
          playerID: "JK-0775",
          playerFirst: "John",
          playerLast: "Kelly",
          playerFull: "John Kelly",
          position: "RB",
          startYear: 2018,
          currentTeam: "LA",
          height: 70,
          weight: 216,
          dob: "10/4/96",
          forty: 4.64,
          bench: 15,
          vertical: 35.0,
          broad: 120,
          shuttle: 4.22,
          cone: 7.13,
          arm: 31.38,
          hand: 9.38,
          dpos: 176.0,
          col: "Tennessee",
          dv: "Southeastern (SEC)",
          jnum: 42,
          dcp: 3,
        },
        {
          playerID: "JM-5275",
          playerFirst: "Joe",
          playerLast: "Mixon",
          playerFull: "Joe Mixon",
          position: "RB",
          startYear: 2017,
          currentTeam: "CIN",
          height: 73,
          weight: 226,
          dob: "7/24/96",
          forty: 4.45,
          bench: 21,
          vertical: 35.0,
          broad: 118,
          shuttle: 4.27,
          cone: 7.1,
          arm: 0.0,
          hand: 0.0,
          dpos: 48.0,
          col: "Oklahoma",
          dv: "Big 12",
          jnum: 28,
          dcp: 1,
        },
        {
          playerID: "JO-0550",
          playerFirst: "Jamize",
          playerLast: "Olawale",
          playerFull: "Jamize Olawale",
          position: "RB",
          startYear: 2012,
          currentTeam: "DAL",
          height: 73,
          weight: 238,
          dob: "4/17/89",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "North Texas",
          dv: "Sun Belt",
          jnum: 49,
          dcp: 1,
        },
        {
          playerID: "JR-2075",
          playerFirst: "Jalen",
          playerLast: "Richard",
          playerFull: "Jalen Richard",
          position: "RB",
          startYear: 2016,
          currentTeam: "OAK",
          height: 68,
          weight: 207,
          dob: "10/15/93",
          forty: 4.6,
          bench: 13,
          vertical: 35.5,
          broad: 114,
          shuttle: 4.95,
          cone: 7.36,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Southern Mississippi",
          dv: "Conference USA (C-USA)",
          jnum: 30,
          dcp: 2,
        },
        {
          playerID: "JS-0280",
          playerFirst: "Jaylen",
          playerLast: "Samuels",
          playerFull: "Jaylen Samuels",
          position: "RB",
          startYear: 2018,
          currentTeam: "PIT",
          height: 71,
          weight: 225,
          dob: "7/20/96",
          forty: 4.54,
          bench: 18,
          vertical: 34.5,
          broad: 121,
          shuttle: 4.28,
          cone: 6.93,
          arm: 31.38,
          hand: 9.25,
          dpos: 165.0,
          col: "North Carolina State",
          dv: "Atlantic Coast (ACC)",
          jnum: 38,
          dcp: 2,
        },
        {
          playerID: "JS-0825",
          playerFirst: "Jordan",
          playerLast: "Scarlett",
          playerFull: "Jordan Scarlett",
          position: "RB",
          startYear: 2019,
          currentTeam: "CAR",
          height: 71,
          weight: 208,
          dob: "2/9/96",
          forty: 4.47,
          bench: 21,
          vertical: 30.0,
          broad: 116,
          shuttle: 4.63,
          cone: 7.37,
          arm: 30.38,
          hand: 9.0,
          dpos: 154.0,
          col: "Florida",
          dv: "Southeastern (SEC)",
          jnum: 20,
          dcp: 3,
        },
        {
          playerID: "JW-2550",
          playerFirst: "James",
          playerLast: "White",
          playerFull: "James White",
          position: "RB",
          startYear: 2014,
          currentTeam: "NE",
          height: 69,
          weight: 204,
          dob: "2/3/92",
          forty: 4.57,
          bench: 23,
          vertical: 32.0,
          broad: 114,
          shuttle: 4.2,
          cone: 7.05,
          arm: 29.25,
          hand: 8.25,
          dpos: 130.0,
          col: "Wisconsin",
          dv: "Big Ten",
          jnum: 28,
          dcp: 1,
        },
        {
          playerID: "JW-3325",
          playerFirst: "Jordan",
          playerLast: "Wilkins",
          playerFull: "Jordan Wilkins",
          position: "RB",
          startYear: 2018,
          currentTeam: "IND",
          height: 73,
          weight: 216,
          dob: "7/18/94",
          forty: 4.71,
          bench: 16,
          vertical: 37.0,
          broad: 123,
          shuttle: 4.22,
          cone: 0.0,
          arm: 30.13,
          hand: 9.38,
          dpos: 169.0,
          col: "Mississippi",
          dv: "Southeastern (SEC)",
          jnum: 20,
          dcp: 3,
        },
        {
          playerID: "JW-3650",
          playerFirst: "Jamaal",
          playerLast: "Williams",
          playerFull: "Jamaal Williams",
          position: "RB",
          startYear: 2017,
          currentTeam: "GB",
          height: 72,
          weight: 212,
          dob: "4/3/95",
          forty: 4.59,
          bench: 18,
          vertical: 33.0,
          broad: 123,
          shuttle: 4.26,
          cone: 7.12,
          arm: 31.25,
          hand: 10.0,
          dpos: 134.0,
          col: "Brigham Young",
          dv: "FBS Independents",
          jnum: 30,
          dcp: 2,
        },
        {
          playerID: "JW-4625",
          playerFirst: "Jonathan",
          playerLast: "Williams",
          playerFull: "Jonathan Williams",
          position: "RB",
          startYear: 2016,
          currentTeam: "IND",
          height: 71,
          weight: 220,
          dob: "2/2/94",
          forty: 4.63,
          bench: 16,
          vertical: 0.0,
          broad: 0,
          shuttle: 4.29,
          cone: 6.97,
          arm: 31.63,
          hand: 10.0,
          dpos: 156.0,
          col: "Arkansas",
          dv: "Southeastern (SEC)",
          jnum: 33,
          dcp: 4,
        },
        {
          playerID: "JW-4975",
          playerFirst: "Jeff",
          playerLast: "Wilson",
          playerFull: "Jeff Wilson",
          position: "RB",
          startYear: 2018,
          currentTeam: "SF",
          height: 71,
          weight: 210,
          dob: "11/16/95",
          forty: 4.6,
          bench: 15,
          vertical: 35.0,
          broad: 110,
          shuttle: 4.29,
          cone: 7.2,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "North Texas",
          dv: "Conference USA (C-USA)",
          jnum: 30,
          dcp: 4,
        },
        {
          playerID: "KB-0150",
          playerFirst: "Kalen",
          playerLast: "Ballage",
          playerFull: "Kalen Ballage",
          position: "RB",
          startYear: 2018,
          currentTeam: "MIA",
          height: 73,
          weight: 228,
          dob: "12/22/95",
          forty: 4.46,
          bench: 15,
          vertical: 33.5,
          broad: 122,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.75,
          hand: 9.5,
          dpos: 131.0,
          col: "Arizona State",
          dv: "Pacific 12",
          jnum: 27,
          dcp: 2,
        },
      ]);
    });
};
