exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("players")
    .then(function () {
      // Inserts seed entries
      return knex("players").insert([
        {
          playerID: "AH-3862",
          playerFirst: "Adam",
          playerLast: "Humphries",
          playerFull: "Adam Humphries",
          position: "WR",
          startYear: 2015,
          currentTeam: "TEN",
          height: 71,
          weight: 190,
          dob: "1/24/93",
          forty: 4.53,
          bench: 14,
          vertical: 32.5,
          broad: 122,
          shuttle: 4.32,
          cone: 6.96,
          arm: 30.0,
          hand: 9.25,
          dpos: 0.0,
          col: "Clemson",
          dv: "Atlantic Coast (ACC)",
          jnum: 10,
          dcp: 1,
        },
        {
          playerID: "AH-3900",
          playerFirst: "Allen",
          playerLast: "Hurns",
          playerFull: "Allen Hurns",
          position: "WR",
          startYear: 2014,
          currentTeam: "MIA",
          height: 73,
          weight: 198,
          dob: "11/12/91",
          forty: 4.54,
          bench: 14,
          vertical: 31.0,
          broad: 120,
          shuttle: 4.5,
          cone: 7.23,
          arm: 32.0,
          hand: 9.25,
          dpos: 0.0,
          col: "Miami (FL)",
          dv: "Atlantic Coast (ACC)",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "AI-0100",
          playerFirst: "Andy",
          playerLast: "Isabella",
          playerFull: "Andy Isabella",
          position: "WR",
          startYear: 2019,
          currentTeam: "ARI",
          height: 69,
          weight: 188,
          dob: "11/18/96",
          forty: 4.45,
          bench: 15,
          vertical: 36.5,
          broad: 121,
          shuttle: 4.15,
          cone: 6.95,
          arm: 29.75,
          hand: 8.38,
          dpos: 62.0,
          col: "Massachusetts",
          dv: "FBS Independents",
          jnum: 89,
          dcp: 2,
        },
        {
          playerID: "AJ-0430",
          playerFirst: "Alshon",
          playerLast: "Jeffery",
          playerFull: "Alshon Jeffery",
          position: "WR",
          startYear: 2012,
          currentTeam: "PHI",
          height: 75,
          weight: 216,
          dob: "2/14/90",
          forty: 4.48,
          bench: 0,
          vertical: 36.5,
          broad: 122,
          shuttle: 4.17,
          cone: 6.71,
          arm: 33.0,
          hand: 10.25,
          dpos: 45.0,
          col: "South Carolina",
          dv: "Southeastern (SEC)",
          jnum: 17,
          dcp: 4,
        },
        {
          playerID: "AL-0387",
          playerFirst: "Allen",
          playerLast: "Lazard",
          playerFull: "Allen Lazard",
          position: "WR",
          startYear: 2018,
          currentTeam: "GB",
          height: 77,
          weight: 227,
          dob: "12/11/95",
          forty: 4.55,
          bench: 17,
          vertical: 38.0,
          broad: 124,
          shuttle: 4.33,
          cone: 7.11,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Iowa State",
          dv: "Big 12",
          jnum: 13,
          dcp: 3,
        },
        {
          playerID: "AM-1975",
          playerFirst: "Anthony",
          playerLast: "Miller",
          playerFull: "Anthony Miller",
          position: "WR",
          startYear: 2018,
          currentTeam: "CHI",
          height: 71,
          weight: 201,
          dob: "10/9/94",
          forty: 4.5,
          bench: 22,
          vertical: 39.0,
          broad: 125,
          shuttle: 4.26,
          cone: 6.65,
          arm: 31.63,
          hand: 10.63,
          dpos: 51.0,
          col: "Memphis",
          dv: "American Athletic",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "AP-0388",
          playerFirst: "Andre",
          playerLast: "Patton",
          playerFull: "Andre Patton",
          position: "WR",
          startYear: 2017,
          currentTeam: "LAC",
          height: 74,
          weight: 206,
          dob: "5/28/94",
          forty: 4.54,
          bench: 10,
          vertical: 35.5,
          broad: 118,
          shuttle: 4.29,
          cone: 6.74,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Rutgers",
          dv: "Big Ten",
          jnum: 15,
          dcp: 2,
        },
        {
          playerID: "AR-1100",
          playerFirst: "Andre",
          playerLast: "Roberts",
          playerFull: "Andre Roberts",
          position: "WR",
          startYear: 2010,
          currentTeam: "BUF",
          height: 71,
          weight: 195,
          dob: "1/9/88",
          forty: 4.4,
          bench: 15,
          vertical: 36.0,
          broad: 120,
          shuttle: 4.15,
          cone: 6.77,
          arm: 31.5,
          hand: 9.5,
          dpos: 88.0,
          col: "Citadel",
          dv: "Southern",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "AR-1250",
          playerFirst: "Allen",
          playerLast: "Robinson",
          playerFull: "Allen Robinson",
          position: "WR",
          startYear: 2014,
          currentTeam: "CHI",
          height: 75,
          weight: 220,
          dob: "8/24/93",
          forty: 4.57,
          bench: 0,
          vertical: 42.0,
          broad: 131,
          shuttle: 4.0,
          cone: 6.54,
          arm: 32.0,
          hand: 9.5,
          dpos: 61.0,
          col: "Penn State",
          dv: "Big Ten",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "AT-0247",
          playerFirst: "Auden",
          playerLast: "Tate",
          playerFull: "Auden Tate",
          position: "WR",
          startYear: 2018,
          currentTeam: "CIN",
          height: 77,
          weight: 228,
          dob: "2/3/97",
          forty: 4.68,
          bench: 0,
          vertical: 31.0,
          broad: 112,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.75,
          hand: 9.38,
          dpos: 253.0,
          col: "Florida State",
          dv: "Atlantic Coast (ACC)",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "AT-0350",
          playerFirst: "Adam",
          playerLast: "Thielen",
          playerFull: "Adam Thielen",
          position: "WR",
          startYear: 2013,
          currentTeam: "MIN",
          height: 75,
          weight: 200,
          dob: "8/22/90",
          forty: 4.54,
          bench: 0,
          vertical: 36.0,
          broad: 120,
          shuttle: 4.49,
          cone: 6.77,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Minnesota State",
          dv: "N/A",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "AW-1650",
          playerFirst: "Albert",
          playerLast: "Wilson",
          playerFull: "Albert Wilson",
          position: "WR",
          startYear: 2014,
          currentTeam: "MIA",
          height: 69,
          weight: 202,
          dob: "7/12/92",
          forty: 4.38,
          bench: 10,
          vertical: 37.5,
          broad: 123,
          shuttle: 4.21,
          cone: 7.0,
          arm: 30.38,
          hand: 9.13,
          dpos: 0.0,
          col: "Georgia State",
          dv: "Sun Belt",
          jnum: 15,
          dcp: 1,
        },
        {
          playerID: "BB-1950",
          playerFirst: "Braxton",
          playerLast: "Berrios",
          playerFull: "Braxton Berrios",
          position: "WR",
          startYear: 2018,
          currentTeam: "NYJ",
          height: 69,
          weight: 184,
          dob: "10/6/95",
          forty: 4.44,
          bench: 11,
          vertical: 36.0,
          broad: 110,
          shuttle: 4.18,
          cone: 6.72,
          arm: 28.0,
          hand: 9.25,
          dpos: 210.0,
          col: "Miami (FL)",
          dv: "Atlantic Coast (ACC)",
          jnum: 10,
          dcp: 2,
        },
        {
          playerID: "BC-2325",
          playerFirst: "Brandin",
          playerLast: "Cooks",
          playerFull: "Brandin Cooks",
          position: "WR",
          startYear: 2014,
          currentTeam: "LA",
          height: 70,
          weight: 189,
          dob: "9/25/93",
          forty: 4.31,
          bench: 16,
          vertical: 36.0,
          broad: 120,
          shuttle: 3.81,
          cone: 6.76,
          arm: 30.75,
          hand: 9.63,
          dpos: 20.0,
          col: "Oregon State",
          dv: "Pacific 12",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "BF-0950",
          playerFirst: "Bennie",
          playerLast: "Fowler",
          playerFull: "Bennie Fowler",
          position: "WR",
          startYear: 2014,
          currentTeam: "INA",
          height: 73,
          weight: 217,
          dob: "6/10/91",
          forty: 4.49,
          bench: 18,
          vertical: 36.0,
          broad: 126,
          shuttle: 4.18,
          cone: 7.06,
          arm: 32.0,
          hand: 9.5,
          dpos: 0.0,
          col: "Michigan State",
          dv: "Big Ten",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "BP-0450",
          playerFirst: "Breshad",
          playerLast: "Perriman",
          playerFull: "Breshad Perriman",
          position: "WR",
          startYear: 2015,
          currentTeam: "TB",
          height: 74,
          weight: 212,
          dob: "9/10/93",
          forty: 4.26,
          bench: 18,
          vertical: 36.5,
          broad: 127,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.0,
          hand: 9.25,
          dpos: 26.0,
          col: "Central Florida",
          dv: "American Athletic",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "BP-1375",
          playerFirst: "Byron",
          playerLast: "Pringle",
          playerFull: "Byron Pringle",
          position: "WR",
          startYear: 2018,
          currentTeam: "KC",
          height: 73,
          weight: 203,
          dob: "11/17/93",
          forty: 4.46,
          bench: 15,
          vertical: 33.5,
          broad: 120,
          shuttle: 4.22,
          cone: 6.87,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Kansas State",
          dv: "Big 12",
          jnum: 13,
          dcp: 3,
        },
        {
          playerID: "BW-2475",
          playerFirst: "Bobo",
          playerLast: "Wilson",
          playerFull: "Bobo Wilson",
          position: "WR",
          startYear: 2017,
          currentTeam: "INA",
          height: 69,
          weight: 189,
          dob: "1/25/95",
          forty: 4.57,
          bench: 10,
          vertical: 0.0,
          broad: 119,
          shuttle: 4.57,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Florida State",
          dv: "Atlantic Coast (ACC)",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "BZ-0100",
          playerFirst: "Brandon",
          playerLast: "Zylstra",
          playerFull: "Brandon Zylstra",
          position: "WR",
          startYear: 2018,
          currentTeam: "CAR",
          height: 74,
          weight: 215,
          dob: "3/25/93",
          forty: 4.64,
          bench: 16,
          vertical: 34.0,
          broad: 128,
          shuttle: 4.54,
          cone: 7.19,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Concordia",
          dv: "N/A",
          jnum: 11,
          dcp: 2,
        },
        {
          playerID: "CB-1130",
          playerFirst: "Cole",
          playerLast: "Beasley",
          playerFull: "Cole Beasley",
          position: "WR",
          startYear: 2012,
          currentTeam: "BUF",
          height: 68,
          weight: 177,
          dob: "4/26/89",
          forty: 4.49,
          bench: 17,
          vertical: 38.0,
          broad: 126,
          shuttle: 4.4,
          cone: 7.16,
          arm: 28.88,
          hand: 0.0,
          dpos: 0.0,
          col: "SMU",
          dv: "Conference USA (C-USA)",
          jnum: 10,
          dcp: 1,
        },
        {
          playerID: "CB-1152",
          playerFirst: "Chad",
          playerLast: "Beebe",
          playerFull: "Chad Beebe",
          position: "WR",
          startYear: 2018,
          currentTeam: "MIN",
          height: 69,
          weight: 185,
          dob: "6/1/94",
          forty: 4.68,
          bench: 0,
          vertical: 32.5,
          broad: 117,
          shuttle: 4.18,
          cone: 6.88,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Northern Illinois",
          dv: "Mid-American (MAC)",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "CB-1650",
          playerFirst: "Christian",
          playerLast: "Blake",
          playerFull: "Christian Blake",
          position: "WR",
          startYear: 2018,
          currentTeam: "ATL",
          height: 73,
          weight: 182,
          dob: "6/8/96",
          forty: 4.55,
          bench: 9,
          vertical: 34.5,
          broad: 126,
          shuttle: 4.4,
          cone: 6.83,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Northern Illinois",
          dv: "Mid-American (MAC)",
          jnum: 13,
          dcp: 3,
        },
        {
          playerID: "CB-1750",
          playerFirst: "C.J.",
          playerLast: "Board",
          playerFull: "C.J. Board",
          position: "WR",
          startYear: 2017,
          currentTeam: "JAC",
          height: 74,
          weight: 174,
          dob: "12/12/93",
          forty: 4.42,
          bench: 9,
          vertical: 38.5,
          broad: 132,
          shuttle: 4.06,
          cone: 6.67,
          arm: 30.63,
          hand: 9.38,
          dpos: 0.0,
          col: "Chattanooga",
          dv: "Southern",
          jnum: 16,
          dcp: 2,
        },
        {
          playerID: "CC-3950",
          playerFirst: "Chris",
          playerLast: "Conley",
          playerFull: "Chris Conley",
          position: "WR",
          startYear: 2015,
          currentTeam: "JAC",
          height: 74,
          weight: 213,
          dob: "10/25/92",
          forty: 4.33,
          bench: 18,
          vertical: 45.0,
          broad: 139,
          shuttle: 4.3,
          cone: 7.06,
          arm: 33.75,
          hand: 9.88,
          dpos: 76.0,
          col: "Georgia",
          dv: "Southeastern (SEC)",
          jnum: 18,
          dcp: 1,
        },
        {
          playerID: "CC-4450",
          playerFirst: "Cody",
          playerLast: "Core",
          playerFull: "Cody Core",
          position: "WR",
          startYear: 2016,
          currentTeam: "NYG",
          height: 75,
          weight: 205,
          dob: "4/17/94",
          forty: 4.37,
          bench: 14,
          vertical: 37.5,
          broad: 119,
          shuttle: 4.34,
          cone: 6.78,
          arm: 32.0,
          hand: 10.38,
          dpos: 199.0,
          col: "Mississippi",
          dv: "Southeastern (SEC)",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "CD-0975",
          playerFirst: "Corey",
          playerLast: "Davis",
          playerFull: "Corey Davis",
          position: "WR",
          startYear: 2017,
          currentTeam: "TEN",
          height: 75,
          weight: 209,
          dob: "1/11/95",
          forty: 4.48,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.0,
          hand: 9.13,
          dpos: 5.0,
          col: "Western Michigan",
          dv: "Mid-American (MAC)",
          jnum: 84,
          dcp: 1,
        },
        {
          playerID: "CG-1425",
          playerFirst: "Chris",
          playerLast: "Godwin",
          playerFull: "Chris Godwin",
          position: "WR",
          startYear: 2017,
          currentTeam: "TB",
          height: 73,
          weight: 209,
          dob: "2/27/96",
          forty: 4.42,
          bench: 19,
          vertical: 36.0,
          broad: 125,
          shuttle: 4.0,
          cone: 7.01,
          arm: 31.63,
          hand: 9.13,
          dpos: 84.0,
          col: "Penn State",
          dv: "Big Ten",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "CG-2162",
          playerFirst: "Cyril",
          playerLast: "Grayson",
          playerFull: "Cyril Grayson",
          position: "WR",
          startYear: 2017,
          currentTeam: "TB",
          height: 69,
          weight: 178,
          dob: "12/5/93",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "LSU",
          dv: "Southeastern (SEC)",
          jnum: 15,
          dcp: 3,
        },
        {
          playerID: "CH-3350",
          playerFirst: "Chris",
          playerLast: "Hogan",
          playerFull: "Chris Hogan",
          position: "WR",
          startYear: 2011,
          currentTeam: "CAR",
          height: 73,
          weight: 215,
          dob: "10/24/88",
          forty: 4.5,
          bench: 28,
          vertical: 36.5,
          broad: 126,
          shuttle: 4.15,
          cone: 6.75,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Monmouth",
          dv: "N/A",
          jnum: 15,
          dcp: 3,
        },
        {
          playerID: "CH-3775",
          playerFirst: "Cody",
          playerLast: "Hollister",
          playerFull: "Cody Hollister",
          position: "WR",
          startYear: 2017,
          currentTeam: "TEN",
          height: 76,
          weight: 209,
          dob: "11/18/93",
          forty: 4.59,
          bench: 24,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Arkansas",
          dv: "Southeastern (SEC)",
          jnum: 16,
          dcp: 2,
        },
        {
          playerID: "CK-0825",
          playerFirst: "Christian",
          playerLast: "Kirk",
          playerFull: "Christian Kirk",
          position: "WR",
          startYear: 2018,
          currentTeam: "ARI",
          height: 70,
          weight: 201,
          dob: "11/18/96",
          forty: 4.47,
          bench: 20,
          vertical: 35.5,
          broad: 115,
          shuttle: 4.45,
          cone: 7.09,
          arm: 30.38,
          hand: 9.88,
          dpos: 47.0,
          col: "Texas A&M",
          dv: "Southeastern (SEC)",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "CK-1300",
          playerFirst: "Cooper",
          playerLast: "Kupp",
          playerFull: "Cooper Kupp",
          position: "WR",
          startYear: 2017,
          currentTeam: "LA",
          height: 74,
          weight: 204,
          dob: "6/15/93",
          forty: 4.62,
          bench: 0,
          vertical: 31.0,
          broad: 115,
          shuttle: 4.08,
          cone: 6.53,
          arm: 31.5,
          hand: 9.5,
          dpos: 69.0,
          col: "Eastern Washington",
          dv: "Big Sky",
          jnum: 18,
          dcp: 1,
        },
        {
          playerID: "CL-0125",
          playerFirst: "Chris",
          playerLast: "Lacy",
          playerFull: "Chris Lacy",
          position: "WR",
          startYear: 2018,
          currentTeam: "DET",
          height: 75,
          weight: 205,
          dob: "1/28/96",
          forty: 4.51,
          bench: 11,
          vertical: 35.5,
          broad: 126,
          shuttle: 4.6,
          cone: 7.29,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Oklahoma State",
          dv: "Big 12",
          jnum: 15,
          dcp: 1,
        },
        {
          playerID: "CL-0275",
          playerFirst: "Cody",
          playerLast: "Latimer",
          playerFull: "Cody Latimer",
          position: "WR",
          startYear: 2014,
          currentTeam: "NYG",
          height: 75,
          weight: 215,
          dob: "10/10/92",
          forty: 4.45,
          bench: 23,
          vertical: 39.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.63,
          hand: 9.63,
          dpos: 56.0,
          col: "Indiana",
          dv: "Big Ten",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "CM-1650",
          playerFirst: "Codey",
          playerLast: "McElroy",
          playerFull: "Codey McElroy",
          position: "WR",
          startYear: 2018,
          currentTeam: "TB",
          height: 78,
          weight: 225,
          dob: "12/13/92",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Southeastern Oklahoma",
          dv: "N/A",
          jnum: 86,
          dcp: 4,
        },
        {
          playerID: "CM-2675",
          playerFirst: "Chris",
          playerLast: "Moore",
          playerFull: "Chris Moore",
          position: "WR",
          startYear: 2016,
          currentTeam: "BAL",
          height: 73,
          weight: 206,
          dob: "6/16/93",
          forty: 4.46,
          bench: 10,
          vertical: 37.0,
          broad: 130,
          shuttle: 4.2,
          cone: 6.76,
          arm: 33.38,
          hand: 9.38,
          dpos: 107.0,
          col: "Cincinnati",
          dv: "American Athletic",
          jnum: 10,
          dcp: 3,
        },
        {
          playerID: "CP-0750",
          playerFirst: "Cordarrelle",
          playerLast: "Patterson",
          playerFull: "Cordarrelle Patterson",
          position: "WR",
          startYear: 2013,
          currentTeam: "CHI",
          height: 74,
          weight: 216,
          dob: "3/17/91",
          forty: 4.33,
          bench: 0,
          vertical: 37.0,
          broad: 128,
          shuttle: 4.4,
          cone: 7.28,
          arm: 31.75,
          hand: 9.0,
          dpos: 29.0,
          col: "Tennessee",
          dv: "Southeastern (SEC)",
          jnum: 84,
          dcp: 2,
        },
        {
          playerID: "CR-0862",
          playerFirst: "Calvin",
          playerLast: "Ridley",
          playerFull: "Calvin Ridley",
          position: "WR",
          startYear: 2018,
          currentTeam: "ATL",
          height: 72,
          weight: 189,
          dob: "12/20/94",
          forty: 4.43,
          bench: 15,
          vertical: 31.0,
          broad: 110,
          shuttle: 4.37,
          cone: 6.88,
          arm: 31.63,
          hand: 9.13,
          dpos: 26.0,
          col: "Alabama",
          dv: "Southeastern (SEC)",
          jnum: 18,
          dcp: 4,
        },
        {
          playerID: "CR-1525",
          playerFirst: "Chester",
          playerLast: "Rogers",
          playerFull: "Chester Rogers",
          position: "WR",
          startYear: 2016,
          currentTeam: "IND",
          height: 73,
          weight: 180,
          dob: "1/12/94",
          forty: 4.51,
          bench: 15,
          vertical: 36.0,
          broad: 120,
          shuttle: 4.07,
          cone: 6.85,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Grambling",
          dv: "Southwestern Athletic (SWAC)",
          jnum: 80,
          dcp: 1,
        },
        {
          playerID: "CS-0050",
          playerFirst: "Curtis",
          playerLast: "Samuel",
          playerFull: "Curtis Samuel",
          position: "WR",
          startYear: 2017,
          currentTeam: "CAR",
          height: 71,
          weight: 196,
          dob: "8/11/96",
          forty: 4.31,
          bench: 18,
          vertical: 37.0,
          broad: 117,
          shuttle: 4.33,
          cone: 7.09,
          arm: 31.25,
          hand: 9.5,
          dpos: 40.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 10,
          dcp: 1,
        },
      ]);
    });
};
