exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("players")
    .then(function () {
      // Inserts seed entries
      return knex("players").insert([
        {
          playerID: "CS-1925",
          playerFirst: "Cam",
          playerLast: "Sims",
          playerFull: "Cam Sims",
          position: "WR",
          startYear: 2018,
          currentTeam: "WAS",
          height: 77,
          weight: 214,
          dob: "1/6/96",
          forty: 4.6,
          bench: 0,
          vertical: 34.0,
          broad: 123,
          shuttle: 4.49,
          cone: 7.57,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Alabama",
          dv: "Southeastern (SEC)",
          jnum: 89,
          dcp: 2,
        },
        {
          playerID: "CS-4462",
          playerFirst: "Courtland",
          playerLast: "Sutton",
          playerFull: "Courtland Sutton",
          position: "WR",
          startYear: 2018,
          currentTeam: "DEN",
          height: 75,
          weight: 218,
          dob: "10/10/95",
          forty: 4.54,
          bench: 18,
          vertical: 35.5,
          broad: 124,
          shuttle: 4.11,
          cone: 6.57,
          arm: 32.38,
          hand: 9.75,
          dpos: 40.0,
          col: "SMU",
          dv: "American Athletic",
          jnum: 14,
          dcp: 1,
        },
        {
          playerID: "CW-2450",
          playerFirst: "Chad",
          playerLast: "Williams",
          playerFull: "Chad Williams",
          position: "WR",
          startYear: 2017,
          currentTeam: "IND",
          height: 73,
          weight: 204,
          dob: "10/19/94",
          forty: 4.43,
          bench: 21,
          vertical: 35.5,
          broad: 123,
          shuttle: 4.21,
          cone: 7.06,
          arm: 32.0,
          hand: 9.75,
          dpos: 98.0,
          col: "Grambling",
          dv: "Southwestern Athletic (SWAC)",
          jnum: 1,
          dcp: 3,
        },
        {
          playerID: "CW-3250",
          playerFirst: "Cedrick",
          playerLast: "Wilson",
          playerFull: "Cedrick Wilson",
          position: "WR",
          startYear: 2018,
          currentTeam: "DAL",
          height: 74,
          weight: 197,
          dob: "11/20/95",
          forty: 4.55,
          bench: 9,
          vertical: 37.0,
          broad: 121,
          shuttle: 4.23,
          cone: 6.89,
          arm: 31.5,
          hand: 9.75,
          dpos: 208.0,
          col: "Boise State",
          dv: "Mountain West (MWC)",
          jnum: 11,
          dcp: 4,
        },
        {
          playerID: "DA-0212",
          playerFirst: "Davante",
          playerLast: "Adams",
          playerFull: "Davante Adams",
          position: "WR",
          startYear: 2014,
          currentTeam: "GB",
          height: 73,
          weight: 212,
          dob: "12/24/92",
          forty: 4.56,
          bench: 14,
          vertical: 39.5,
          broad: 127,
          shuttle: 4.3,
          cone: 6.82,
          arm: 32.63,
          hand: 9.0,
          dpos: 53.0,
          col: "Fresno State",
          dv: "Mountain West (MWC)",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "DA-0900",
          playerFirst: "Danny",
          playerLast: "Amendola",
          playerFull: "Danny Amendola",
          position: "WR",
          startYear: 2008,
          currentTeam: "DET",
          height: 70,
          weight: 186,
          dob: "11/2/85",
          forty: 4.68,
          bench: 13,
          vertical: 31.5,
          broad: 103,
          shuttle: 4.25,
          cone: 6.81,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Texas Tech",
          dv: "Big 12",
          jnum: 80,
          dcp: 1,
        },
        {
          playerID: "DB-5912",
          playerFirst: "Deontay",
          playerLast: "Burnett",
          playerFull: "Deontay Burnett",
          position: "WR",
          startYear: 2018,
          currentTeam: "PHI",
          height: 72,
          weight: 186,
          dob: "10/4/97",
          forty: 4.43,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "USC",
          dv: "Pacific 12",
          jnum: 82,
          dcp: 2,
        },
        {
          playerID: "DB-6375",
          playerFirst: "Damiere",
          playerLast: "Byrd",
          playerFull: "Damiere Byrd",
          position: "WR",
          startYear: 2015,
          currentTeam: "ARI",
          height: 69,
          weight: 162,
          dob: "1/27/93",
          forty: 4.27,
          bench: 13,
          vertical: 42.0,
          broad: 131,
          shuttle: 4.09,
          cone: 6.59,
          arm: 29.88,
          hand: 8.0,
          dpos: 0.0,
          col: "South Carolina",
          dv: "Southeastern (SEC)",
          jnum: 14,
          dcp: 1,
        },
        {
          playerID: "DC-0025",
          playerFirst: "Deon",
          playerLast: "Cain",
          playerFull: "Deon Cain",
          position: "WR",
          startYear: 2018,
          currentTeam: "PIT",
          height: 74,
          weight: 202,
          dob: "8/9/96",
          forty: 4.43,
          bench: 11,
          vertical: 33.5,
          broad: 115,
          shuttle: 4.37,
          cone: 6.71,
          arm: 33.0,
          hand: 8.75,
          dpos: 185.0,
          col: "Clemson",
          dv: "Atlantic Coast (ACC)",
          jnum: 17,
          dcp: 3,
        },
        {
          playerID: "DC-1050",
          playerFirst: "DeAndre",
          playerLast: "Carter",
          playerFull: "DeAndre Carter",
          position: "WR",
          startYear: 2015,
          currentTeam: "HOU",
          height: 69,
          weight: 191,
          dob: "4/10/93",
          forty: 4.44,
          bench: 17,
          vertical: 38.5,
          broad: 126,
          shuttle: 3.8,
          cone: 6.64,
          arm: 30.63,
          hand: 8.75,
          dpos: 0.0,
          col: "Sacramento State",
          dv: "Big Sky",
          jnum: 14,
          dcp: 2,
        },
        {
          playerID: "DC-1418",
          playerFirst: "D.J.",
          playerLast: "Chark",
          playerFull: "D.J. Chark",
          position: "WR",
          startYear: 2018,
          currentTeam: "JAC",
          height: 75,
          weight: 199,
          dob: "9/23/96",
          forty: 4.34,
          bench: 16,
          vertical: 40.0,
          broad: 129,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.38,
          hand: 9.25,
          dpos: 61.0,
          col: "LSU",
          dv: "Southeastern (SEC)",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "DF-2200",
          playerFirst: "Devin",
          playerLast: "Funchess",
          playerFull: "Devin Funchess",
          position: "WR",
          startYear: 2015,
          currentTeam: "IND",
          height: 76,
          weight: 232,
          dob: "5/21/94",
          forty: 4.5,
          bench: 17,
          vertical: 38.5,
          broad: 122,
          shuttle: 4.48,
          cone: 6.98,
          arm: 33.5,
          hand: 9.75,
          dpos: 41.0,
          col: "Michigan",
          dv: "Big Ten",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "DH-1050",
          playerFirst: "DaeSean",
          playerLast: "Hamilton",
          playerFull: "DaeSean Hamilton",
          position: "WR",
          startYear: 2018,
          currentTeam: "DEN",
          height: 73,
          weight: 203,
          dob: "3/10/95",
          forty: 4.52,
          bench: 16,
          vertical: 34.5,
          broad: 123,
          shuttle: 4.15,
          cone: 6.84,
          arm: 31.0,
          hand: 9.38,
          dpos: 113.0,
          col: "Penn State",
          dv: "Big Ten",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "DH-1487",
          playerFirst: "Deonte",
          playerLast: "Harris",
          playerFull: "Deonte Harris",
          position: "WR",
          startYear: 2019,
          currentTeam: "NO",
          height: 66,
          weight: 170,
          dob: "12/4/97",
          forty: 4.48,
          bench: 10,
          vertical: 33.0,
          broad: 114,
          shuttle: 4.16,
          cone: 6.82,
          arm: 28.25,
          hand: 8.75,
          dpos: 0.0,
          col: "Assumption",
          dv: "N/A",
          jnum: 11,
          dcp: 2,
        },
        {
          playerID: "DH-1800",
          playerFirst: "Dwayne",
          playerLast: "Harris",
          playerFull: "Dwayne Harris",
          position: "WR",
          startYear: 2011,
          currentTeam: "OAK",
          height: 70,
          weight: 200,
          dob: "9/16/87",
          forty: 4.53,
          bench: 10,
          vertical: 34.0,
          broad: 111,
          shuttle: 4.21,
          cone: 6.77,
          arm: 31.13,
          hand: 10.13,
          dpos: 176.0,
          col: "East Carolina",
          dv: "Conference USA (C-USA)",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "DH-3950",
          playerFirst: "DeAndre",
          playerLast: "Hopkins",
          playerFull: "DeAndre Hopkins",
          position: "WR",
          startYear: 2013,
          currentTeam: "HOU",
          height: 73,
          weight: 214,
          dob: "6/6/92",
          forty: 4.51,
          bench: 15,
          vertical: 36.0,
          broad: 115,
          shuttle: 4.5,
          cone: 6.83,
          arm: 33.38,
          hand: 10.0,
          dpos: 27.0,
          col: "Clemson",
          dv: "Atlantic Coast (ACC)",
          jnum: 10,
          dcp: 1,
        },
        {
          playerID: "DI-0075",
          playerFirst: "Dontrelle",
          playerLast: "Inman",
          playerFull: "Dontrelle Inman",
          position: "WR",
          startYear: 2011,
          currentTeam: "IND",
          height: 75,
          weight: 198,
          dob: "1/31/89",
          forty: 4.5,
          bench: 11,
          vertical: 34.0,
          broad: 118,
          shuttle: 4.13,
          cone: 6.53,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Virginia",
          dv: "Atlantic Coast (ACC)",
          jnum: 86,
          dcp: 3,
        },
        {
          playerID: "DJ-0200",
          playerFirst: "DeSean",
          playerLast: "Jackson",
          playerFull: "DeSean Jackson",
          position: "WR",
          startYear: 2008,
          currentTeam: "PHI",
          height: 70,
          weight: 175,
          dob: "12/1/86",
          forty: 4.35,
          bench: 0,
          vertical: 34.5,
          broad: 122,
          shuttle: 4.19,
          cone: 6.82,
          arm: 31.25,
          hand: 9.38,
          dpos: 49.0,
          col: "California",
          dv: "Pacific 10",
          jnum: 10,
          dcp: 2,
        },
        {
          playerID: "DJ-0850",
          playerFirst: "Darius",
          playerLast: "Jennings",
          playerFull: "Darius Jennings",
          position: "WR",
          startYear: 2015,
          currentTeam: "TEN",
          height: 71,
          weight: 175,
          dob: "6/28/92",
          forty: 4.47,
          bench: 0,
          vertical: 37.0,
          broad: 123,
          shuttle: 4.29,
          cone: 6.95,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Virginia",
          dv: "Atlantic Coast (ACC)",
          jnum: 15,
          dcp: 3,
        },
        {
          playerID: "DJ-1675",
          playerFirst: "Diontae",
          playerLast: "Johnson",
          playerFull: "Diontae Johnson",
          position: "WR",
          startYear: 2019,
          currentTeam: "PIT",
          height: 70,
          weight: 183,
          dob: "7/5/96",
          forty: 4.53,
          bench: 15,
          vertical: 33.5,
          broad: 123,
          shuttle: 4.45,
          cone: 7.09,
          arm: 30.75,
          hand: 9.0,
          dpos: 66.0,
          col: "Toledo",
          dv: "Mid-American (MAC)",
          jnum: 18,
          dcp: 1,
        },
        {
          playerID: "DM-2275",
          playerFirst: "D.K.",
          playerLast: "Metcalf",
          playerFull: "D.K. Metcalf",
          position: "WR",
          startYear: 2019,
          currentTeam: "SEA",
          height: 75,
          weight: 228,
          dob: "12/14/97",
          forty: 4.33,
          bench: 27,
          vertical: 40.5,
          broad: 134,
          shuttle: 4.5,
          cone: 7.38,
          arm: 34.88,
          hand: 9.88,
          dpos: 64.0,
          col: "Mississippi",
          dv: "Southeastern (SEC)",
          jnum: 14,
          dcp: 1,
        },
        {
          playerID: "DM-2775",
          playerFirst: "Donte",
          playerLast: "Moncrief",
          playerFull: "Donte Moncrief",
          position: "WR",
          startYear: 2014,
          currentTeam: "INA",
          height: 74,
          weight: 221,
          dob: "8/6/93",
          forty: 4.34,
          bench: 13,
          vertical: 39.5,
          broad: 132,
          shuttle: 4.3,
          cone: 7.02,
          arm: 32.38,
          hand: 9.13,
          dpos: 90.0,
          col: "Mississippi",
          dv: "Southeastern (SEC)",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "DM-2850",
          playerFirst: "D.J.",
          playerLast: "Moore",
          playerFull: "D.J. Moore",
          position: "WR",
          startYear: 2018,
          currentTeam: "CAR",
          height: 72,
          weight: 210,
          dob: "4/14/97",
          forty: 4.42,
          bench: 15,
          vertical: 39.5,
          broad: 132,
          shuttle: 4.07,
          cone: 6.95,
          arm: 31.63,
          hand: 9.63,
          dpos: 24.0,
          col: "Maryland",
          dv: "Big Ten",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "DM-3050",
          playerFirst: "David",
          playerLast: "Moore",
          playerFull: "David Moore",
          position: "WR",
          startYear: 2017,
          currentTeam: "SEA",
          height: 74,
          weight: 225,
          dob: "1/15/95",
          forty: 4.43,
          bench: 26,
          vertical: 36.5,
          broad: 124,
          shuttle: 4.38,
          cone: 6.98,
          arm: 0.0,
          hand: 0.0,
          dpos: 226.0,
          col: "East Central Oklahoma",
          dv: "N/A",
          jnum: 83,
          dcp: 2,
        },
        {
          playerID: "DP-0350",
          playerFirst: "DeVante",
          playerLast: "Parker",
          playerFull: "DeVante Parker",
          position: "WR",
          startYear: 2015,
          currentTeam: "MIA",
          height: 75,
          weight: 209,
          dob: "1/20/93",
          forty: 4.4,
          bench: 17,
          vertical: 36.5,
          broad: 125,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.25,
          hand: 9.25,
          dpos: 14.0,
          col: "Louisville",
          dv: "Atlantic Coast (ACC)",
          jnum: 11,
          dcp: 1,
        },
        {
          playerID: "DP-1263",
          playerFirst: "Dante",
          playerLast: "Pettis",
          playerFull: "Dante Pettis",
          position: "WR",
          startYear: 2018,
          currentTeam: "SF",
          height: 72,
          weight: 186,
          dob: "10/23/95",
          forty: 4.49,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.25,
          hand: 9.5,
          dpos: 44.0,
          col: "Washington",
          dv: "Pacific 12",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "DR-0550",
          playerFirst: "Damion",
          playerLast: "Ratley",
          playerFull: "Damion Ratley",
          position: "WR",
          startYear: 2018,
          currentTeam: "CLE",
          height: 73,
          weight: 193,
          dob: "4/16/95",
          forty: 4.42,
          bench: 12,
          vertical: 38.0,
          broad: 124,
          shuttle: 4.23,
          cone: 6.92,
          arm: 0.0,
          hand: 0.0,
          dpos: 175.0,
          col: "Texas A&M",
          dv: "Southeastern (SEC)",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "DR-2225",
          playerFirst: "Demarcus",
          playerLast: "Robinson",
          playerFull: "Demarcus Robinson",
          position: "WR",
          startYear: 2016,
          currentTeam: "KC",
          height: 73,
          weight: 203,
          dob: "9/21/94",
          forty: 4.56,
          bench: 9,
          vertical: 34.5,
          broad: 123,
          shuttle: 4.19,
          cone: 6.69,
          arm: 33.0,
          hand: 9.5,
          dpos: 126.0,
          col: "Florida",
          dv: "Southeastern (SEC)",
          jnum: 11,
          dcp: 2,
        },
        {
          playerID: "DS-0150",
          playerFirst: "Deebo",
          playerLast: "Samuel",
          playerFull: "Deebo Samuel",
          position: "WR",
          startYear: 2019,
          currentTeam: "SF",
          height: 71,
          weight: 214,
          dob: "1/15/96",
          forty: 4.48,
          bench: 15,
          vertical: 39.0,
          broad: 122,
          shuttle: 4.14,
          cone: 7.03,
          arm: 31.38,
          hand: 10.0,
          dpos: 36.0,
          col: "South Carolina",
          dv: "Southeastern (SEC)",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "DS-0875",
          playerFirst: "Da'Mari",
          playerLast: "Scott",
          playerFull: "Da'Mari Scott",
          position: "WR",
          startYear: 2018,
          currentTeam: "NYG",
          height: 73,
          weight: 205,
          dob: "8/8/95",
          forty: 4.52,
          bench: 10,
          vertical: 32.5,
          broad: 116,
          shuttle: 4.27,
          cone: 6.86,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Fresno State",
          dv: "Mountain West (MWC)",
          jnum: 5,
          dcp: 3,
        },
        {
          playerID: "DS-1862",
          playerFirst: "Darrius",
          playerLast: "Shepherd",
          playerFull: "Darrius Shepherd",
          position: "WR",
          startYear: 2019,
          currentTeam: "GB",
          height: 70,
          weight: 185,
          dob: "11/1/95",
          forty: 4.61,
          bench: 14,
          vertical: 35.5,
          broad: 120,
          shuttle: 4.4,
          cone: 7.13,
          arm: 30.0,
          hand: 10.0,
          dpos: 0.0,
          col: "North Dakota State",
          dv: "Missouri Valley",
          jnum: 10,
          dcp: 5,
        },
        {
          playerID: "DS-2275",
          playerFirst: "Darius",
          playerLast: "Slayton",
          playerFull: "Darius Slayton",
          position: "WR",
          startYear: 2019,
          currentTeam: "NYG",
          height: 73,
          weight: 190,
          dob: "1/12/97",
          forty: 4.39,
          bench: 11,
          vertical: 40.5,
          broad: 135,
          shuttle: 4.15,
          cone: 7.0,
          arm: 32.75,
          hand: 10.0,
          dpos: 171.0,
          col: "Auburn",
          dv: "Southeastern (SEC)",
          jnum: 86,
          dcp: 2,
        },
        {
          playerID: "DS-3031",
          playerFirst: "Devin",
          playerLast: "Smith",
          playerFull: "Devin Smith",
          position: "WR",
          startYear: 2015,
          currentTeam: "DAL",
          height: 72,
          weight: 196,
          dob: "3/3/92",
          forty: 4.37,
          bench: 10,
          vertical: 39.0,
          broad: 122,
          shuttle: 4.15,
          cone: 6.83,
          arm: 31.0,
          hand: 9.0,
          dpos: 37.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 15,
          dcp: 2,
        },
        {
          playerID: "DS-3187",
          playerFirst: "Diontae",
          playerLast: "Spencer",
          playerFull: "Diontae Spencer",
          position: "WR",
          startYear: 2014,
          currentTeam: "DEN",
          height: 69,
          weight: 161,
          dob: "3/19/92",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "McNeese",
          dv: "Southland",
          jnum: 11,
          dcp: 2,
        },
        {
          playerID: "DT-0850",
          playerFirst: "De'Anthony",
          playerLast: "Thomas",
          playerFull: "De'Anthony Thomas",
          position: "WR",
          startYear: 2014,
          currentTeam: "BAL",
          height: 69,
          weight: 174,
          dob: "1/5/93",
          forty: 4.43,
          bench: 8,
          vertical: 32.5,
          broad: 123,
          shuttle: 4.23,
          cone: 6.94,
          arm: 29.88,
          hand: 8.13,
          dpos: 124.0,
          col: "Oregon",
          dv: "Pacific 12",
          jnum: 84,
          dcp: 4,
        },
        {
          playerID: "DT-0900",
          playerFirst: "Demaryius",
          playerLast: "Thomas",
          playerFull: "Demaryius Thomas",
          position: "WR",
          startYear: 2010,
          currentTeam: "NYJ",
          height: 75,
          weight: 229,
          dob: "12/25/87",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.0,
          hand: 10.5,
          dpos: 22.0,
          col: "Georgia Tech",
          dv: "Atlantic Coast (ACC)",
          jnum: 18,
          dcp: 1,
        },
        {
          playerID: "DW-2275",
          playerFirst: "Dede",
          playerLast: "Westbrook",
          playerFull: "Dede Westbrook",
          position: "WR",
          startYear: 2017,
          currentTeam: "JAC",
          height: 72,
          weight: 178,
          dob: "11/21/93",
          forty: 4.39,
          bench: 8,
          vertical: 34.5,
          broad: 120,
          shuttle: 4.34,
          cone: 7.2,
          arm: 30.63,
          hand: 9.0,
          dpos: 110.0,
          col: "Oklahoma",
          dv: "Big 12",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "DW-2350",
          playerFirst: "DeAndrew",
          playerLast: "White",
          playerFull: "DeAndrew White",
          position: "WR",
          startYear: 2015,
          currentTeam: "CAR",
          height: 71,
          weight: 191,
          dob: "10/16/91",
          forty: 4.4,
          bench: 0,
          vertical: 36.0,
          broad: 121,
          shuttle: 4.18,
          cone: 6.97,
          arm: 31.0,
          hand: 9.13,
          dpos: 0.0,
          col: "Alabama",
          dv: "Southeastern (SEC)",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "DW-2850",
          playerFirst: "D'haquille",
          playerLast: "Williams",
          playerFull: "D'haquille Williams",
          position: "WR",
          startYear: 2016,
          currentTeam: "BUF",
          height: 74,
          weight: 224,
          dob: "5/13/93",
          forty: 4.68,
          bench: 14,
          vertical: 30.5,
          broad: 121,
          shuttle: 4.47,
          cone: 7.43,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Auburn",
          dv: "Southeastern (SEC)",
          jnum: 82,
          dcp: 2,
        },
        {
          playerID: "DW-3987",
          playerFirst: "Damion",
          playerLast: "Willis",
          playerFull: "Damion Willis",
          position: "WR",
          startYear: 2019,
          currentTeam: "CIN",
          height: 75,
          weight: 195,
          dob: "6/20/97",
          forty: 4.51,
          bench: 13,
          vertical: 33.5,
          broad: 110,
          shuttle: 4.5,
          cone: 7.04,
          arm: 33.25,
          hand: 8.88,
          dpos: 0.0,
          col: "Troy",
          dv: "Sun Belt",
          jnum: 15,
          dcp: 2,
        },
      ]);
    });
};
