exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("players")
    .then(function () {
      // Inserts seed entries
      return knex("players").insert([
        {
          playerID: "JW-1050",
          playerFirst: "Justin",
          playerLast: "Watson",
          playerFull: "Justin Watson",
          position: "WR",
          startYear: 2018,
          currentTeam: "TB",
          height: 75,
          weight: 213,
          dob: "4/4/95",
          forty: 4.45,
          bench: 20,
          vertical: 40.0,
          broad: 124,
          shuttle: 4.26,
          cone: 7.08,
          arm: 0.0,
          hand: 0.0,
          dpos: 144.0,
          col: "Pennsylvania",
          dv: "Ivy League",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "JW-5475",
          playerFirst: "Javon",
          playerLast: "Wims",
          playerFull: "Javon Wims",
          position: "WR",
          startYear: 2018,
          currentTeam: "CHI",
          height: 75,
          weight: 215,
          dob: "9/11/94",
          forty: 4.53,
          bench: 0,
          vertical: 33.5,
          broad: 113,
          shuttle: 0.0,
          cone: 7.0,
          arm: 31.5,
          hand: 9.25,
          dpos: 224.0,
          col: "Georgia",
          dv: "Southeastern (SEC)",
          jnum: 83,
          dcp: 2,
        },
        {
          playerID: "JW-5637",
          playerFirst: "Juwann",
          playerLast: "Winfree",
          playerFull: "Juwann Winfree",
          position: "WR",
          startYear: 2019,
          currentTeam: "DEN",
          height: 73,
          weight: 212,
          dob: "9/4/96",
          forty: 4.53,
          bench: 16,
          vertical: 33.0,
          broad: 125,
          shuttle: 4.25,
          cone: 6.97,
          arm: 31.5,
          hand: 9.75,
          dpos: 187.0,
          col: "Colorado",
          dv: "Pacific 12",
          jnum: 15,
          dcp: 1,
        },
        {
          playerID: "JW-6560",
          playerFirst: "Jarius",
          playerLast: "Wright",
          playerFull: "Jarius Wright",
          position: "WR",
          startYear: 2012,
          currentTeam: "CAR",
          height: 70,
          weight: 180,
          dob: "11/25/89",
          forty: 4.39,
          bench: 11,
          vertical: 38.0,
          broad: 120,
          shuttle: 4.03,
          cone: 6.93,
          arm: 31.5,
          hand: 8.5,
          dpos: 118.0,
          col: "Arkansas",
          dv: "Southeastern (SEC)",
          jnum: 13,
          dcp: 2,
        },
        {
          playerID: "KA-0650",
          playerFirst: "Keenan",
          playerLast: "Allen",
          playerFull: "Keenan Allen",
          position: "WR",
          startYear: 2013,
          currentTeam: "LAC",
          height: 74,
          weight: 206,
          dob: "4/27/92",
          forty: 4.58,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.75,
          hand: 10.0,
          dpos: 76.0,
          col: "California",
          dv: "Pacific 12",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "KB-1625",
          playerFirst: "Kendrick",
          playerLast: "Bourne",
          playerFull: "Kendrick Bourne",
          position: "WR",
          startYear: 2017,
          currentTeam: "SF",
          height: 74,
          weight: 190,
          dob: "8/4/95",
          forty: 4.68,
          bench: 10,
          vertical: 36.0,
          broad: 124,
          shuttle: 4.21,
          cone: 6.73,
          arm: 32.5,
          hand: 9.13,
          dpos: 0.0,
          col: "Eastern Washington",
          dv: "Big Sky",
          jnum: 84,
          dcp: 2,
        },
        {
          playerID: "KC-1550",
          playerFirst: "Keelan",
          playerLast: "Cole",
          playerFull: "Keelan Cole",
          position: "WR",
          startYear: 2017,
          currentTeam: "JAC",
          height: 74,
          weight: 175,
          dob: "4/20/93",
          forty: 4.59,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 4.4,
          cone: 6.69,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Kentucky Wesleyan",
          dv: "N/A",
          jnum: 84,
          dcp: 2,
        },
        {
          playerID: "KC-2375",
          playerFirst: "Keke",
          playerLast: "Coutee",
          playerFull: "Keke Coutee",
          position: "WR",
          startYear: 2018,
          currentTeam: "HOU",
          height: 70,
          weight: 181,
          dob: "1/14/97",
          forty: 4.43,
          bench: 14,
          vertical: 34.5,
          broad: 113,
          shuttle: 4.15,
          cone: 6.93,
          arm: 29.88,
          hand: 8.38,
          dpos: 103.0,
          col: "Texas Tech",
          dv: "Big 12",
          jnum: 16,
          dcp: 2,
        },
        {
          playerID: "KD-1456",
          playerFirst: "Keelan",
          playerLast: "Doss",
          playerFull: "Keelan Doss",
          position: "WR",
          startYear: 2019,
          currentTeam: "OAK",
          height: 74,
          weight: 211,
          dob: "3/21/96",
          forty: 4.57,
          bench: 8,
          vertical: 36.0,
          broad: 124,
          shuttle: 0.0,
          cone: 0.0,
          arm: 31.5,
          hand: 9.5,
          dpos: 0.0,
          col: "California-Davis",
          dv: "Big Sky",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "KG-0650",
          playerFirst: "Kenny",
          playerLast: "Golladay",
          playerFull: "Kenny Golladay",
          position: "WR",
          startYear: 2017,
          currentTeam: "DET",
          height: 76,
          weight: 218,
          dob: "11/3/93",
          forty: 4.5,
          bench: 18,
          vertical: 35.5,
          broad: 120,
          shuttle: 4.15,
          cone: 7.0,
          arm: 32.0,
          hand: 9.75,
          dpos: 96.0,
          col: "Northern Illinois",
          dv: "Mid-American (MAC)",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "KH-0525",
          playerFirst: "Kelvin",
          playerLast: "Harmon",
          playerFull: "Kelvin Harmon",
          position: "WR",
          startYear: 2019,
          currentTeam: "WAS",
          height: 74,
          weight: 221,
          dob: "12/15/96",
          forty: 4.6,
          bench: 18,
          vertical: 32.5,
          broad: 117,
          shuttle: 4.32,
          cone: 7.15,
          arm: 32.5,
          hand: 9.5,
          dpos: 206.0,
          col: "North Carolina State",
          dv: "Atlantic Coast (ACC)",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "KH-2025",
          playerFirst: "Khadarel",
          playerLast: "Hodge",
          playerFull: "Khadarel Hodge",
          position: "WR",
          startYear: 2018,
          currentTeam: "CLE",
          height: 74,
          weight: 201,
          dob: "1/3/95",
          forty: 4.59,
          bench: 0,
          vertical: 38.0,
          broad: 124,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Prairie View",
          dv: "N/A",
          jnum: 12,
          dcp: 2,
        },
        {
          playerID: "KH-2075",
          playerFirst: "Krishawn",
          playerLast: "Hogan",
          playerFull: "Krishawn Hogan",
          position: "WR",
          startYear: 2017,
          currentTeam: "NO",
          height: 75,
          weight: 213,
          dob: "5/12/95",
          forty: 4.56,
          bench: 13,
          vertical: 36.5,
          broad: 123,
          shuttle: 4.21,
          cone: 6.74,
          arm: 32.13,
          hand: 9.88,
          dpos: 0.0,
          col: "Marian",
          dv: "N/A",
          jnum: 81,
          dcp: 5,
        },
        {
          playerID: "KJ-0537",
          playerFirst: "KeeSean",
          playerLast: "Johnson",
          playerFull: "KeeSean Johnson",
          position: "WR",
          startYear: 2019,
          currentTeam: "ARI",
          height: 73,
          weight: 201,
          dob: "10/9/96",
          forty: 4.53,
          bench: 14,
          vertical: 30.0,
          broad: 117,
          shuttle: 4.23,
          cone: 7.28,
          arm: 32.13,
          hand: 9.63,
          dpos: 174.0,
          col: "Fresno State",
          dv: "Mountain West (MWC)",
          jnum: 19,
          dcp: 2,
        },
        {
          playerID: "KR-0312",
          playerFirst: "Kalif",
          playerLast: "Raymond",
          playerFull: "Kalif Raymond",
          position: "WR",
          startYear: 2016,
          currentTeam: "TEN",
          height: 69,
          weight: 160,
          dob: "8/8/94",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Holy Cross",
          dv: "N/A",
          jnum: 14,
          dcp: 2,
        },
        {
          playerID: "KS-2350",
          playerFirst: "Kenny",
          playerLast: "Stills",
          playerFull: "Kenny Stills",
          position: "WR",
          startYear: 2013,
          currentTeam: "HOU",
          height: 72,
          weight: 194,
          dob: "4/22/92",
          forty: 4.38,
          bench: 16,
          vertical: 33.5,
          broad: 124,
          shuttle: 4.13,
          cone: 7.13,
          arm: 30.5,
          hand: 9.0,
          dpos: 144.0,
          col: "Oklahoma",
          dv: "Big 12",
          jnum: 12,
          dcp: 1,
        },
        {
          playerID: "LF-0200",
          playerFirst: "Larry",
          playerLast: "Fitzgerald",
          playerFull: "Larry Fitzgerald",
          position: "WR",
          startYear: 2004,
          currentTeam: "ARI",
          height: 75,
          weight: 218,
          dob: "8/31/83",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 10.5,
          dpos: 3.0,
          col: "Pittsburgh",
          dv: "Big East",
          jnum: 11,
          dcp: 1,
        },
        {
          playerID: "LH-1950",
          playerFirst: "Lil'Jordan",
          playerLast: "Humphrey",
          playerFull: "Lil'Jordan Humphrey",
          position: "WR",
          startYear: 2019,
          currentTeam: "NO",
          height: 76,
          weight: 210,
          dob: "4/19/98",
          forty: 4.75,
          bench: 13,
          vertical: 33.5,
          broad: 119,
          shuttle: 4.29,
          cone: 7.09,
          arm: 32.75,
          hand: 9.5,
          dpos: 0.0,
          col: "Texas",
          dv: "Big 12",
          jnum: 84,
          dcp: 3,
        },
        {
          playerID: "LT-0862",
          playerFirst: "Laquon",
          playerLast: "Treadwell",
          playerFull: "Laquon Treadwell",
          position: "WR",
          startYear: 2016,
          currentTeam: "MIN",
          height: 74,
          weight: 221,
          dob: "6/14/95",
          forty: 4.64,
          bench: 12,
          vertical: 33.5,
          broad: 117,
          shuttle: 4.3,
          cone: 7.04,
          arm: 33.38,
          hand: 9.5,
          dpos: 23.0,
          col: "Mississippi",
          dv: "Southeastern (SEC)",
          jnum: 11,
          dcp: 3,
        },
        {
          playerID: "MA-1287",
          playerFirst: "Marcell",
          playerLast: "Ateman",
          playerFull: "Marcell Ateman",
          position: "WR",
          startYear: 2018,
          currentTeam: "OAK",
          height: 76,
          weight: 216,
          dob: "9/16/94",
          forty: 4.62,
          bench: 13,
          vertical: 34.0,
          broad: 121,
          shuttle: 4.25,
          cone: 7.07,
          arm: 32.88,
          hand: 9.88,
          dpos: 228.0,
          col: "Oklahoma State",
          dv: "Big 12",
          jnum: 88,
          dcp: 4,
        },
        {
          playerID: "MB-3325",
          playerFirst: "Miles",
          playerLast: "Boykin",
          playerFull: "Miles Boykin",
          position: "WR",
          startYear: 2019,
          currentTeam: "BAL",
          height: 76,
          weight: 220,
          dob: "10/12/96",
          forty: 4.42,
          bench: 12,
          vertical: 43.5,
          broad: 140,
          shuttle: 4.07,
          cone: 6.77,
          arm: 33.5,
          hand: 9.88,
          dpos: 93.0,
          col: "Notre Dame",
          dv: "FBS Independents",
          jnum: 80,
          dcp: 1,
        },
        {
          playerID: "MB-4075",
          playerFirst: "Marquise",
          playerLast: "Brown",
          playerFull: "Marquise Brown",
          position: "WR",
          startYear: 2019,
          currentTeam: "BAL",
          height: 69,
          weight: 166,
          dob: "6/4/97",
          forty: 4.34,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 30.5,
          hand: 9.0,
          dpos: 25.0,
          col: "Oklahoma",
          dv: "Big 12",
          jnum: 15,
          dcp: 1,
        },
        {
          playerID: "MC-2900",
          playerFirst: "Michael",
          playerLast: "Crabtree",
          playerFull: "Michael Crabtree",
          position: "WR",
          startYear: 2009,
          currentTeam: "INA",
          height: 73,
          weight: 214,
          dob: "9/14/87",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 34.25,
          hand: 9.25,
          dpos: 10.0,
          col: "Texas Tech",
          dv: "Big 12",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "ME-0600",
          playerFirst: "Mike",
          playerLast: "Evans",
          playerFull: "Mike Evans",
          position: "WR",
          startYear: 2014,
          currentTeam: "TB",
          height: 77,
          weight: 231,
          dob: "8/21/93",
          forty: 4.46,
          bench: 12,
          vertical: 37.0,
          broad: 0,
          shuttle: 4.26,
          cone: 7.08,
          arm: 35.13,
          hand: 9.38,
          dpos: 7.0,
          col: "Texas A&M",
          dv: "Southeastern (SEC)",
          jnum: 13,
          dcp: 3,
        },
        {
          playerID: "MG-0175",
          playerFirst: "Michael",
          playerLast: "Gallup",
          playerFull: "Michael Gallup",
          position: "WR",
          startYear: 2018,
          currentTeam: "DAL",
          height: 73,
          weight: 205,
          dob: "3/4/96",
          forty: 4.51,
          bench: 10,
          vertical: 36.0,
          broad: 122,
          shuttle: 4.37,
          cone: 6.95,
          arm: 31.5,
          hand: 9.25,
          dpos: 81.0,
          col: "Colorado State",
          dv: "Mountain West (MWC)",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "MG-1050",
          playerFirst: "Marquise",
          playerLast: "Goodwin",
          playerFull: "Marquise Goodwin",
          position: "WR",
          startYear: 2013,
          currentTeam: "SF",
          height: 69,
          weight: 183,
          dob: "11/19/90",
          forty: 4.21,
          bench: 13,
          vertical: 42.0,
          broad: 135,
          shuttle: 4.09,
          cone: 6.66,
          arm: 31.5,
          hand: 8.63,
          dpos: 78.0,
          col: "Texas",
          dv: "Big 12",
          jnum: 11,
          dcp: 4,
        },
        {
          playerID: "MH-0225",
          playerFirst: "Marvin",
          playerLast: "Hall",
          playerFull: "Marvin Hall",
          position: "WR",
          startYear: 2016,
          currentTeam: "DET",
          height: 70,
          weight: 188,
          dob: "4/10/93",
          forty: 4.4,
          bench: 15,
          vertical: 40.0,
          broad: 125,
          shuttle: 4.24,
          cone: 6.86,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Washington",
          dv: "Pacific 12",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "MH-0875",
          playerFirst: "Mecole",
          playerLast: "Hardman",
          playerFull: "Mecole Hardman",
          position: "WR",
          startYear: 2019,
          currentTeam: "KC",
          height: 70,
          weight: 187,
          dob: "3/12/98",
          forty: 4.33,
          bench: 17,
          vertical: 36.5,
          broad: 119,
          shuttle: 4.25,
          cone: 6.75,
          arm: 30.25,
          hand: 9.0,
          dpos: 56.0,
          col: "Georgia",
          dv: "Southeastern (SEC)",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "MH-3050",
          playerFirst: "Mack",
          playerLast: "Hollins",
          playerFull: "Mack Hollins",
          position: "WR",
          startYear: 2017,
          currentTeam: "MIA",
          height: 76,
          weight: 221,
          dob: "9/16/93",
          forty: 4.53,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.25,
          hand: 9.75,
          dpos: 118.0,
          col: "North Carolina",
          dv: "Atlantic Coast (ACC)",
          jnum: 86,
          dcp: 3,
        },
        {
          playerID: "MJ-1450",
          playerFirst: "Marcus",
          playerLast: "Johnson",
          playerFull: "Marcus Johnson",
          position: "WR",
          startYear: 2016,
          currentTeam: "IND",
          height: 72,
          weight: 192,
          dob: "8/5/94",
          forty: 4.34,
          bench: 22,
          vertical: 37.0,
          broad: 135,
          shuttle: 4.39,
          cone: 7.26,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Texas",
          dv: "Big 12",
          jnum: 83,
          dcp: 2,
        },
        {
          playerID: "MJ-2250",
          playerFirst: "Marvin",
          playerLast: "Jones",
          playerFull: "Marvin Jones",
          position: "WR",
          startYear: 2012,
          currentTeam: "DET",
          height: 74,
          weight: 200,
          dob: "3/12/90",
          forty: 4.46,
          bench: 22,
          vertical: 33.0,
          broad: 112,
          shuttle: 4.11,
          cone: 6.81,
          arm: 33.13,
          hand: 10.25,
          dpos: 166.0,
          col: "California",
          dv: "Pacific 12",
          jnum: 11,
          dcp: 4,
        },
        {
          playerID: "ML-0650",
          playerFirst: "Marqise",
          playerLast: "Lee",
          playerFull: "Marqise Lee",
          position: "WR",
          startYear: 2014,
          currentTeam: "JAC",
          height: 72,
          weight: 192,
          dob: "11/25/91",
          forty: 4.52,
          bench: 0,
          vertical: 38.0,
          broad: 127,
          shuttle: 4.01,
          cone: 6.96,
          arm: 31.75,
          hand: 9.5,
          dpos: 39.0,
          col: "USC",
          dv: "Pacific 12",
          jnum: 11,
          dcp: 1,
        },
        {
          playerID: "MS-0150",
          playerFirst: "Mohamed",
          playerLast: "Sanu",
          playerFull: "Mohamed Sanu",
          position: "WR",
          startYear: 2012,
          currentTeam: "NE",
          height: 73,
          weight: 211,
          dob: "8/22/89",
          forty: 4.62,
          bench: 19,
          vertical: 36.0,
          broad: 126,
          shuttle: 4.22,
          cone: 6.88,
          arm: 33.5,
          hand: 10.13,
          dpos: 83.0,
          col: "Rutgers",
          dv: "Big East",
          jnum: 14,
          dcp: 2,
        },
        {
          playerID: "MS-2100",
          playerFirst: "Matthew",
          playerLast: "Slater",
          playerFull: "Matthew Slater",
          position: "WR",
          startYear: 2008,
          currentTeam: "NE",
          height: 72,
          weight: 200,
          dob: "9/9/85",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 153.0,
          col: "UCLA",
          dv: "Pacific 10",
          jnum: 18,
          dcp: 3,
        },
        {
          playerID: "MT-0875",
          playerFirst: "Michael",
          playerLast: "Thomas",
          playerFull: "Michael Thomas",
          position: "WR",
          startYear: 2016,
          currentTeam: "NO",
          height: 75,
          weight: 212,
          dob: "3/3/93",
          forty: 4.52,
          bench: 18,
          vertical: 35.0,
          broad: 126,
          shuttle: 4.13,
          cone: 6.8,
          arm: 32.13,
          hand: 10.5,
          dpos: 47.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "MT-0887",
          playerFirst: "Mike",
          playerLast: "Thomas",
          playerFull: "Mike Thomas",
          position: "WR",
          startYear: 2016,
          currentTeam: "LA",
          height: 73,
          weight: 193,
          dob: "3/3/93",
          forty: 4.54,
          bench: 16,
          vertical: 36.0,
          broad: 126,
          shuttle: 4.26,
          cone: 7.06,
          arm: 0.0,
          hand: 0.0,
          dpos: 206.0,
          col: "Southern Mississippi",
          dv: "Conference USA (C-USA)",
          jnum: 88,
          dcp: 2,
        },
        {
          playerID: "MT-2350",
          playerFirst: "Malik",
          playerLast: "Turner",
          playerFull: "Malik Turner",
          position: "WR",
          startYear: 2018,
          currentTeam: "SEA",
          height: 75,
          weight: 205,
          dob: "1/30/96",
          forty: 0.0,
          bench: 17,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Illinois",
          dv: "Big Ten",
          jnum: 17,
          dcp: 3,
        },
        {
          playerID: "MV-0012",
          playerFirst: "Marquez",
          playerLast: "Valdes-Scantling",
          playerFull: "Marquez Valdes-Scantling",
          position: "WR",
          startYear: 2018,
          currentTeam: "GB",
          height: 76,
          weight: 206,
          dob: "10/10/94",
          forty: 4.37,
          bench: 15,
          vertical: 30.5,
          broad: 124,
          shuttle: 4.17,
          cone: 6.85,
          arm: 32.25,
          hand: 10.25,
          dpos: 174.0,
          col: "South Florida",
          dv: "American Athletic",
          jnum: 83,
          dcp: 1,
        },
        {
          playerID: "MW-0350",
          playerFirst: "Michael",
          playerLast: "Walker",
          playerFull: "Michael Walker",
          position: "WR",
          startYear: 2019,
          currentTeam: "JAC",
          height: 72,
          weight: 200,
          dob: "10/29/96",
          forty: 4.48,
          bench: 21,
          vertical: 36.5,
          broad: 130,
          shuttle: 4.49,
          cone: 6.96,
          arm: 30.75,
          hand: 9.0,
          dpos: 0.0,
          col: "Boston College",
          dv: "Atlantic Coast (ACC)",
          jnum: 13,
          dcp: 2,
        },
        {
          playerID: "MW-2825",
          playerFirst: "Mike",
          playerLast: "Williams",
          playerFull: "Mike Williams",
          position: "WR",
          startYear: 2017,
          currentTeam: "LAC",
          height: 76,
          weight: 218, 
          dob: "10/4/94",
          forty: 4.54,
          bench: 15,
          vertical: 32.5,
          broad: 121,
          shuttle: 0.0,
          cone: 0.0,
          arm: 33.38,
          hand: 9.38,
          dpos: 7.0,
          col: "Clemson",
          dv: "Atlantic Coast (ACC)",
          jnum: 81,
          dcp: 1,
        },
      ]);
    });
};
