exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("players")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("players").insert([
        {
          playerID: "TG-0025",
          playerFirst: "Taylor",
          playerLast: "Gabriel",
          playerFull: "Taylor Gabriel",
          position: "WR",
          startYear: 2014,
          currentTeam: "CHI",
          height: 67,
          weight: 167,
          dob: "2/17/91",
          forty: 4.4,
          bench: 17,
          vertical: 40.0,
          broad: 125,
          shuttle: 4.21,
          cone: 6.84,
          arm: 29.75,
          hand: 8.38,
          dpos: 0.0,
          col: "Abilene Christian",
          dv: "FCS Independents",
          jnum: 18,
          dcp: 1,
        },
        {
          playerID: "TG-0900",
          playerFirst: "Ted",
          playerLast: "Ginn",
          playerFull: "Ted Ginn",
          position: "WR",
          startYear: 2007,
          currentTeam: "NO",
          height: 71,
          weight: 180,
          dob: "4/12/85",
          forty: 0.0,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 31.25,
          hand: 9.13,
          dpos: 9.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "TH-1750",
          playerFirst: "Tyreek",
          playerLast: "Hill",
          playerFull: "Tyreek Hill",
          position: "WR",
          startYear: 2016,
          currentTeam: "KC",
          height: 68,
          weight: 185,
          dob: "3/1/94",
          forty: 4.29,
          bench: 13,
          vertical: 40.5,
          broad: 129,
          shuttle: 4.06,
          cone: 6.53,
          arm: 0.0,
          hand: 0.0,
          dpos: 165.0,
          col: "West Alabama",
          dv: "N/A",
          jnum: 10,
          dcp: 1,
        },
        {
          playerID: "TH-1850",
          playerFirst: "T.Y.",
          playerLast: "Hilton",
          playerFull: "T.Y. Hilton",
          position: "WR",
          startYear: 2012,
          currentTeam: "IND",
          height: 69,
          weight: 183,
          dob: "11/14/89",
          forty: 4.37,
          bench: 0,
          vertical: 0.0,
          broad: 0,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.0,
          hand: 8.5,
          dpos: 92.0,
          col: "Florida International",
          dv: "Sun Belt",
          jnum: 13,
          dcp: 1,
        },
        {
          playerID: "TJ-2350",
          playerFirst: "T.J.",
          playerLast: "Jones",
          playerFull: "T.J. Jones",
          position: "WR",
          startYear: 2014,
          currentTeam: "INA",
          height: 72,
          weight: 188,
          dob: "7/19/92",
          forty: 4.46,
          bench: 0,
          vertical: 33.0,
          broad: 119,
          shuttle: 4.27,
          cone: 6.82,
          arm: 30.63,
          hand: 10.0,
          dpos: 189.0,
          col: "Notre Dame",
          dv: "FBS Independents",
          jnum: 0,
          dcp: 0,
        },
        {
          playerID: "TJ-2650",
          playerFirst: "Tevin",
          playerLast: "Jones",
          playerFull: "Tevin Jones",
          position: "WR",
          startYear: 2016,
          currentTeam: "DAL",
          height: 74,
          weight: 218,
          dob: "12/26/92",
          forty: 4.48,
          bench: 18,
          vertical: 36.5,
          broad: 125,
          shuttle: 4.18,
          cone: 6.88,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Memphis",
          dv: "American Athletic",
          jnum: 0,
          dcp: 4,
        },
        {
          playerID: "TL-1025",
          playerFirst: "Tyler",
          playerLast: "Lockett",
          playerFull: "Tyler Lockett",
          position: "WR",
          startYear: 2015,
          currentTeam: "SEA",
          height: 70,
          weight: 182,
          dob: "9/28/92",
          forty: 4.31,
          bench: 0,
          vertical: 35.5,
          broad: 121,
          shuttle: 4.07,
          cone: 6.89,
          arm: 30.0,
          hand: 8.38,
          dpos: 69.0,
          col: "Kansas State",
          dv: "Big 12",
          jnum: 16,
          dcp: 1,
        },
        {
          playerID: "TM-2275",
          playerFirst: "Terry",
          playerLast: "McLaurin",
          playerFull: "Terry McLaurin",
          position: "WR",
          startYear: 2019,
          currentTeam: "WAS",
          height: 72,
          weight: 208,
          dob: "4/15/96",
          forty: 4.35,
          bench: 18,
          vertical: 37.5,
          broad: 125,
          shuttle: 4.15,
          cone: 7.01,
          arm: 31.5,
          hand: 9.13,
          dpos: 76.0,
          col: "Ohio State",
          dv: "Big Ten",
          jnum: 17,
          dcp: 1,
        },
        {
          playerID: "TP-0675",
          playerFirst: "Tim",
          playerLast: "Patrick",
          playerFull: "Tim Patrick",
          position: "WR",
          startYear: 2017,
          currentTeam: "DEN",
          height: 77,
          weight: 210,
          dob: "11/23/93",
          forty: 4.47,
          bench: 22,
          vertical: 37.5,
          broad: 128,
          shuttle: 4.38,
          cone: 6.99,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Utah",
          dv: "Pacific 12",
          jnum: 81,
          dcp: 1,
        },
        {
          playerID: "TQ-0100",
          playerFirst: "Trey",
          playerLast: "Quinn",
          playerFull: "Trey Quinn",
          position: "WR",
          startYear: 2018,
          currentTeam: "WAS",
          height: 71,
          weight: 203,
          dob: "12/7/95",
          forty: 4.46,
          bench: 17,
          vertical: 33.5,
          broad: 104,
          shuttle: 4.17,
          cone: 6.91,
          arm: 30.75,
          hand: 10.13,
          dpos: 256.0,
          col: "SMU",
          dv: "American Athletic",
          jnum: 18,
          dcp: 2,
        },
        {
          playerID: "TS-1262",
          playerFirst: "Tajae",
          playerLast: "Sharpe",
          playerFull: "Tajae Sharpe",
          position: "WR",
          startYear: 2016,
          currentTeam: "TEN",
          height: 74,
          weight: 194,
          dob: "12/23/94",
          forty: 4.49,
          bench: 11,
          vertical: 33.5,
          broad: 114,
          shuttle: 0.0,
          cone: 0.0,
          arm: 32.25,
          hand: 8.38,
          dpos: 140.0,
          col: "Massachusetts",
          dv: "Mid-American (MAC)",
          jnum: 19,
          dcp: 1,
        },
        {
          playerID: "TS-1425",
          playerFirst: "Trent",
          playerLast: "Sherfield",
          playerFull: "Trent Sherfield",
          position: "WR",
          startYear: 2018,
          currentTeam: "ARI",
          height: 72,
          weight: 200,
          dob: "2/26/96",
          forty: 4.48,
          bench: 19,
          vertical: 32.5,
          broad: 125,
          shuttle: 4.2,
          cone: 6.9,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Vanderbilt",
          dv: "Southeastern (SEC)",
          jnum: 16,
          dcp: 2,
        },
        {
          playerID: "TS-2425",
          playerFirst: "Tre'Quan",
          playerLast: "Smith",
          playerFull: "Tre'Quan Smith",
          position: "WR",
          startYear: 2018,
          currentTeam: "NO",
          height: 74,
          weight: 203,
          dob: "1/7/96",
          forty: 4.49,
          bench: 12,
          vertical: 37.5,
          broad: 130,
          shuttle: 4.5,
          cone: 6.97,
          arm: 33.38,
          hand: 9.5,
          dpos: 91.0,
          col: "Central Florida",
          dv: "American Athletic",
          jnum: 10,
          dcp: 2,
        },
        {
          playerID: "TT-0150",
          playerFirst: "Taywan",
          playerLast: "Taylor",
          playerFull: "Taywan Taylor",
          position: "WR",
          startYear: 2017,
          currentTeam: "CLE",
          height: 71,
          weight: 203,
          dob: "3/2/95",
          forty: 4.5,
          bench: 13,
          vertical: 38.0,
          broad: 132,
          shuttle: 4.21,
          cone: 6.57,
          arm: 32.63,
          hand: 9.25,
          dpos: 72.0,
          col: "Western Kentucky",
          dv: "Conference USA (C-USA)",
          jnum: 10,
          dcp: 3,
        },
        {
          playerID: "TW-2875",
          playerFirst: "Tyrell",
          playerLast: "Williams",
          playerFull: "Tyrell Williams",
          position: "WR",
          startYear: 2015,
          currentTeam: "OAK",
          height: 76,
          weight: 200,
          dob: "2/12/92",
          forty: 4.43,
          bench: 0,
          vertical: 39.5,
          broad: 127,
          shuttle: 4.17,
          cone: 6.74,
          arm: 33.5,
          hand: 9.88,
          dpos: 0.0,
          col: "Western Oregon",
          dv: "N/A",
          jnum: 16,
          dcp: 1,
        },
        {
          playerID: "VB-0325",
          playerFirst: "Ventell",
          playerLast: "Bryant",
          playerFull: "Ventell Bryant",
          position: "WR",
          startYear: 2019,
          currentTeam: "DAL",
          height: 75,
          weight: 198,
          dob: "8/24/96",
          forty: 4.61,
          bench: 12,
          vertical: 34.5,
          broad: 121,
          shuttle: 4.25,
          cone: 6.97,
          arm: 33.13,
          hand: 9.75,
          dpos: 0.0,
          col: "Temple",
          dv: "American Athletic",
          jnum: 83,
          dcp: 3,
        },
        {
          playerID: "VS-0175",
          playerFirst: "Vyncint",
          playerLast: "Smith",
          playerFull: "Vyncint Smith",
          position: "WR",
          startYear: 2018,
          currentTeam: "NYJ",
          height: 75,
          weight: 195,
          dob: "6/9/96",
          forty: 4.38,
          bench: 0,
          vertical: 39.5,
          broad: 130,
          shuttle: 4.27,
          cone: 6.89,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Limestone",
          dv: "N/A",
          jnum: 17,
          dcp: 2,
        },
        {
          playerID: "WF-0300",
          playerFirst: "Will",
          playerLast: "Fuller",
          playerFull: "Will Fuller",
          position: "WR",
          startYear: 2016,
          currentTeam: "HOU",
          height: 72,
          weight: 186,
          dob: "4/16/94",
          forty: 4.28,
          bench: 10,
          vertical: 33.5,
          broad: 126,
          shuttle: 4.27,
          cone: 6.93,
          arm: 30.75,
          hand: 8.25,
          dpos: 21.0,
          col: "Notre Dame",
          dv: "FBS Independents",
          jnum: 15,
          dcp: 1,
        },
        {
          playerID: "WS-0925",
          playerFirst: "Willie",
          playerLast: "Snead",
          playerFull: "Willie Snead",
          position: "WR",
          startYear: 2014,
          currentTeam: "BAL",
          height: 71,
          weight: 195,
          dob: "10/17/92",
          forty: 4.56,
          bench: 11,
          vertical: 36.0,
          broad: 119,
          shuttle: 4.38,
          cone: 7.18,
          arm: 33.0,
          hand: 10.25,
          dpos: 0.0,
          col: "Ball State",
          dv: "Mid-American (MAC)",
          jnum: 83,
          dcp: 2,
        },
        {
          playerID: "ZJ-0100",
          playerFirst: "Zay",
          playerLast: "Jones",
          playerFull: "Zay Jones",
          position: "WR",
          startYear: 2017,
          currentTeam: "OAK",
          height: 74,
          weight: 201,
          dob: "3/30/95",
          forty: 4.45,
          bench: 15,
          vertical: 36.5,
          broad: 133,
          shuttle: 4.01,
          cone: 6.79,
          arm: 32.5,
          hand: 9.0,
          dpos: 37.0,
          col: "East Carolina",
          dv: "American Athletic",
          jnum: 81,
          dcp: 1,
        },
        {
          playerID: "ZP-0050",
          playerFirst: "Zach",
          playerLast: "Pascal",
          playerFull: "Zach Pascal",
          position: "WR",
          startYear: 2017,
          currentTeam: "IND",
          height: 74,
          weight: 207,
          dob: "12/18/94",
          forty: 4.55,
          bench: 14,
          vertical: 36.0,
          broad: 125,
          shuttle: 4.25,
          cone: 7.11,
          arm: 0.0,
          hand: 0.0,
          dpos: 0.0,
          col: "Old Dominion",
          dv: "Conference USA (C-USA)",
          jnum: 14,
          dcp: 1,
        },
      ]);
    });
};
